### ISSUE TITLE
10.2.2-irc Maximum Transfer

### ISSUE THREAD

**Issue by daygle** [fastcoinproject/fastcoin#27]
10.2.2-irc only allows a maximum transfer of 100 fastcoin.

Is there anyway to increase the maximum?

**Comment by Stouse49** [comment]
The limit is not on the number of fastcoins, but rather the size of the transaction in bytes.

**Comment by daygle** [comment]
Closing case as I have discontinued fastcoin as the blockchain is too large.

**Comment by zesterer** [comment]
Perhaps I'm misunderstanding, but from my limited knowledge of blockchain technology, it should be possible to periodically remove initial blockchain history given full network consensus: the equivalent of a git commit squash.
