### ISSUE TITLE
After Start fastcoind auto stop

### ISSUE THREAD

**Issue by shoaib39** [fastcoinproject/fastcoin#35]
when i Start Fastcoin Deamon, after few second its auto start all the times, after installing this 
#apt-get libdb5.3++ . Without libdb other Coin not starting so i had installed, after install this fastcoin stop after few seconds. Its happen only in your new updates.

Thank you

**Comment by fastcoinproject** [comment]
Thank you shoaib39 for your comment.  I recently sent you an invite as a collaborator.  Please feel free to connect and perhaps we can review this together in more detail if you like.

**Comment by shoaib39** [comment]
I found the problem, what was that. 
Problem was, between Block syc if we stop fastboot deamon or rebooting system then Block or something data corrupt in The -> root/.fastcoin/Blocks Directory.

So after many experiments i found the solution by Deleting only Blocks or .fastcoin/Blocks Directory, 
And Configure again the deamon fastcoin.config then start deamon like fastcoind, and syc will start from begnning.

But blocks syc was very slow happening in 1 hrs 1% ir more, is there are any boosting method to fast syc?

**Comment by fastcoinproject** [comment]
Thank you shaib39 for the update, yes we are working on an automated bootstrap file.  Feel free to manually download the master block files from here if you like...
https://drive.google.com/drive/folders/0B_wr62ugl5IaY3ZybkFadEJiR3M

**Comment by fastcoinproject** [comment]
This documentation may provide you greater insight as to how we wish to automate this process moving forward...
https://github.com/fastcoinproject/fastcoin/wiki/bootstrap

**Comment by shoaib39** [comment]
No i asking for Coin mining Pool deamon Syc Block, very slow.

**Comment by fastcoinproject** [comment]
Thank you for clarifying shaib39, not sure what maybe causing this, we will investigate
